apiVersion: apps/v1
kind: Deployment
metadata:
  name: cobol-process
  labels:
    app: cobol-process
spec:
  selector:
    matchLabels:
      app: cobol-process
  template:
    metadata:
      labels:
        app: cobol-process
    spec:
      containers:
      - image: jjasghar/cobol-batch:v1.9
        name: cobol-process
        volumeMounts:
        - name: k8s-cobol
          mountPath: /mnt/

      volumes:
      - name: k8s-cobol
        persistentVolumeClaim:
          claimName: k8s-cobol
