apiVersion: apps/v1
kind: Deployment
metadata:
  name: workhorse
  labels:
    app: workhorse
spec:
  selector:
    matchLabels:
      app: workhorse
  template:
    metadata:
      labels:
        app: workhorse
    spec:
      containers:
      - image: jjasghar/fedora:v1.1
        name: workhorse
        volumeMounts:
        - name: k8s-cobol
          mountPath: /mnt/
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]

      volumes:
      - name: k8s-cobol
        persistentVolumeClaim:
          claimName: k8s-cobol
