apiVersion: apps/v1
kind: Deployment
metadata:
  name: watcher-in
  labels:
    app: watcher-in
spec:
  selector:
    matchLabels:
      app: watcher-in
  template:
    metadata:
      labels:
        app: watcher-in
    spec:
      containers:
      - image: jjasghar/watcher-in:v1.6
        name: watcher-in
        volumeMounts:
        - name: k8s-cobol
          mountPath: /mnt/

      volumes:
      - name: k8s-cobol
        persistentVolumeClaim:
          claimName: k8s-cobol
